version: '3.8'

services:
  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=mysql://root:your_password@db:3306/tasks_db
      - RUST_LOG=info
      - ONESIGNAL_APP_ID=${ONESIGNAL_APP_ID}
      - ONESIGNAL_REST_API_KEY=${ONESIGNAL_REST_API_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=tasks_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

